name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python ./generate.py --no-edit --package --debug --output ./build
      - uses: actions/upload-artifact@v4
        with:
          name: missions
          path: ./build
